title: Databases DevRoom at FOSDEM 2026
description: We’re excited to announce the Databases devroom for FOSDEM 2026
show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
